version: '3.8'
services:
  db:
    image: postgres:15
    container_name: nail-salon-db
    environment:
      POSTGRES_DB: nail_salon
      POSTGRES_USER: nail_admin
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - nail_salon_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nail-salon-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Optional: Database GUI
  adminer:
    image: adminer:latest
    container_name: nail-salon-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  nail_salon_data:
  redis_data: